#!/usr/bin/env bash
payload=$(cat <<EOF
{
  "id": "${PROJECT_PATH_ID}_Journey_${JOURNEY_NAME}",
  "name": "${JOURNEY_NAME}",
  "projectId": "${PROJECT_PATH_ID}",
  "template": {
    "id": "${PROJECT_PATH_ID}_JourneyTemplate"
  }
}
EOF
)

echo $payload

curl -i -sS --fail-with-body \
  -H "Authorization: Bearer ${GIT_PAT_TOKEN}" \
  -H "Content-Type: application/json" \
  -X POST \
  "${TEAMCITY_SERVER_URL}/app/rest/buildTypes" \
  -d "${payload}"