#!/usr/bin/env bash
set -euo pipefail

echo "##teamcity[buildStatus status='RUNNING' text='Click here to create journey!']"

wget \
  --method=POST \
  -qO- http://localhost:3002/code  \
    | jq -r '.code' > "${JOURNEY_NAME}_script.py"