package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with absolute id = 'FirstProject_FirstBuildConfiguration'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id = AbsoluteId("FirstProject_FirstBuildConfiguration")
    name = "FirstBuildConfiguration"
    description = "first build configuration i've ever made"

    steps {
        script {
            name = "Call an endpoint"
            id = "Call_an_endpoint"
            scriptContent = """
                set -e
                
                curl --fail --silent --show-error \
                     --request POST \
                     http://localhost:8070/runJourney/WEB_1.txt/WEB
            """.trimIndent()
        }
    }
}))

