package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.triggers.vcs
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'JourneyExecutor'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("JourneyExecutor")) {
    check(artifactRules == "+:app-jar.jar") {
        "Unexpected option value: artifactRules = $artifactRules"
    }
    artifactRules = "+:**/app-all.jar"

    triggers {
        add {
            vcs {
                branchFilter = ""
            }
        }
    }
}
