package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Journey_SixthGeneratedBuild9'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    templates(RelativeId("JourneyExecutorTemplate"))
    id("Journey_SixthGeneratedBuild9")
    name = "SixthGeneratedBuild9"

    artifactRules = """
        *.csv
        SixthGeneratedBuild5.txt
        +:**/*
    """.trimIndent()

    params {
        param("journeyName", "ceva")
    }

    steps {
        script {
            name = "Run Journey"
            id = "TEMPLATE_RUNNER_1"
            enabled = false
            scriptContent = "wget -O insights2.csv https://docs.google.com/spreadsheets/d/e/2PACX-1vSk39A_ZgQ0pofEIvYgrNdq6p9-wZ3kwWoHcMx5ln6D9MpTpY919y412D14BRNLHRVDXZ-YMug2WHWE/pub?output=csv"
        }
        script {
            name = "Save Report"
            id = "TEMPLATE_RUNNER_2"
            enabled = false
            scriptContent = "ls -alR > folder_tree-after-download.log"
        }
        script {
            id = "simpleRunner"
            enabled = false
            scriptContent = """
                rm -rf configs
                mkdir configs
                
                find "config-repo" -iname "javagroundtruthinsights*.*" -print | while read file; do
                    base=${'$'}(basename "${'$'}file")
                    mv -- "${'$'}file" "configs/config_${'$'}base"
                done
                if [ -z "${'$'}(ls -A configs)" ]; then
                    mv -- config-repo/default/default.csv "configs/config_javagroundtruthinsights.csv"
                fi
            """.trimIndent()
        }
    }

    dependencies {
        artifacts(RelativeId("JourneyMakerV1")) {
            id = "ARTIFACT_DEPENDENCY_4"
            buildRule = build("70")
            artifactRules = "SixthGeneratedBuild5.txt"
        }
    }
}))

