package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.swabra
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Journey_HybridJourney'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    templates(RelativeId("JourneyTemplate"))
    id("Journey_HybridJourney")
    name = "HybridJourney"

    params {
        param("JOURNEY_NAME", "HybridJourney")
        param("JOURNEY_TYPE", "ANDROID")
    }

    features {
        swabra {
            id = "swabra"
        }
    }

    dependencies {
        artifacts(RelativeId("JourneyGenerator")) {
            id = "ARTIFACT_DEPENDENCY_29"
            buildRule = build("87")
            artifactRules = "HybridJourney_script.py=>script"
        }
    }

    requirements {
        contains("env.COMPATIBLE_JOURNEY_TYPES", "ANDROID", "RQ_29")
    }
}))

