package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.swabra
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Journey_Journey9'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    templates(RelativeId("JourneyTemplate"))
    id("Journey_Journey9")
    name = "Journey9"

    params {
        param("JOURNEY_NAME", "Journey9")
        param("JOURNEY_TYPE", "WEB")
    }

    features {
        swabra {
            id = "swabra"
        }
    }

    dependencies {
        artifacts(RelativeId("JourneyGenerator")) {
            id = "ARTIFACT_DEPENDENCY_10"
            buildRule = build("49")
            artifactRules = "Journey9_script.py=>script"
        }
    }

    requirements {
        contains("env.COMPATIBLE_JOURNEY_TYPES", "WEB", "RQ_10")
    }
}))

