package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'JourneyGenerator'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("JourneyGenerator")) {
    expectSteps {
        script {
            id = "JourneyGeneration/Generate Journey Script"
            scriptContent = """
                #!/usr/bin/env bash
                set -euo pipefail
                
                wget \
                  --method=POST \
                  -qO- http://localhost:3002/code  \
                    | jq -r '.code' > "${'$'}{JOURNEY_NAME}_script.py"
            """.trimIndent()
        }
        script {
            id = "Generate Journey build configuration"
            scriptContent = """
                #!/usr/bin/env bash
                payload=${'$'}{'${'$'}'}(cat <<EOF
                {
                  "id"        : "${'$'}{'${'$'}'}{PROJECT_PATH_ID}_Journey_${'$'}{'${'$'}'}{JOURNEY_NAME}",
                  "name"      : "${'$'}{'${'$'}'}{JOURNEY_NAME}",
                  "projectId" : "${'$'}{'${'$'}'}{PROJECT_PATH_ID}",
                  "template": { "id": "${'$'}{'${'$'}'}{PROJECT_PATH_ID}t_JourneyExecutorTemplate" },
                    "artifact-dependencies": {
                    "count": 1,
                    "artifact-dependency": [
                      {
                        "id": "ARTIFACT_DEPENDENCY_JOURNEY_SCRIPT",
                        "type": "artifact_dependency",
                        "properties": {
                          "property": [
                            {
                              "name": "cleanDestinationDirectory",
                              "value": "false"
                            },
                            {
                              "name": "pathRules",
                              "value": "${'$'}{'${'$'}'}{JOURNEY_NAME}_script.py=>script"
                            },
                            {
                              "name": "revisionName",
                              "value": "buildNumber"
                            },
                            {
                              "name": "revisionValue",
                              "value": "%system.build.number%"
                            }
                          ],
                          "count": 4
                        },
                        "source-buildType": {
                          "id": "%system.teamcity.buildType.id%"
                        }
                      }
                    ]
                  },
                 "features": {
                    "count": 1,
                    "feature": [
                      {
                        "id": "swabra",
                        "type": "swabra",
                        "properties": {
                          "property": [
                            {
                              "name": "swabra.enabled",
                              "value": "swabra.before.build"
                            }
                          ],
                          "count": 1
                        }
                      }
                    ]
                  },
                    "agent-requirements": {
                    "count": 1,
                    "agent-requirement": [
                      {
                        "id": "RQ_6",
                        "type": "contains",
                        "properties": {
                          "property": [
                            {
                              "name": "property-name",
                              "value": "env.COMPATIBLE_JOURNEY_TYPES"
                            },
                            {
                              "name": "property-value",
                              "value": "%JOURNEY_TYPE%"
                            }
                          ],
                          "count": 2
                        }
                      }
                    ]
                  }
                }
                EOF
                )
                
                curl -i -sS \
                  -H "Authorization: Bearer ${'$'}{'${'$'}'}{GIT_PAT_TOKEN}" \
                  -H "Content-Type: application/json" \
                  -X POST \
                  "${'$'}{'${'$'}'}{TEAMCITY_SERVER_URL}/app/rest/buildTypes" \
                  -d "${'$'}{'${'$'}'}{payload}"
            """.trimIndent()
        }
    }
    steps {
        insert(2) {
            script {
                id = "simpleRunner"
                scriptContent = """echo "%test.param%""""
            }
        }
    }
}
