package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.swabra
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Journey_Journey4'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    templates(RelativeId("JourneyExecutorTemplate"))
    id("Journey_Journey4")
    name = "Journey4"

    params {
        param("env.BUILD_AGENT_HOME", "%teamcity.agent.home.dir%")
        param("env.AGENT_WORK_DIR", "%teamcity.build.workingDir%")
        param("env.CHECKOUT_DIR", "%teamcity.build.checkoutDir%")
    }

    steps {
        script {
            id = "simpleRunner"
            scriptContent = """
                echo 'thse are the env variables'
                echo ${'$'}{CHECKOUT_DIR}
                echo '%teamcity.build.checkoutDir%'
            """.trimIndent()
        }
    }

    features {
        swabra {
            id = "swabra"
        }
    }

    dependencies {
        artifacts(RelativeId("JourneyMakerV1")) {
            id = "ARTIFACT_DEPENDENCY_24"
            buildRule = build("109")
            artifactRules = "Journey4_script.py=>script"
        }
    }

    requirements {
        contains("env.COMPATIBLE_JOURNEY_TYPES", "WEB", "RQ_21")
    }
}))

