package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Journey_SixthGeneratedBuild19'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    templates(RelativeId("JourneyExecutorTemplate"))
    id("Journey_SixthGeneratedBuild19")
    name = "SixthGeneratedBuild19"

    dependencies {
        artifacts(RelativeId("JourneyMakerV1")) {
            id = "ARTIFACT_DEPENDENCY_13"
            buildRule = build("93")
            artifactRules = "SixthGeneratedBuild19_script.txt=>script"
        }
    }

    requirements {
        contains("env.COMPATIBLE_JOURNEY_TYPES", "WEB", "RQ_10")
    }
}))

