package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'JourneyGenerator'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("JourneyGenerator")) {
    expectSteps {
        script {
            id = "journeyGeneration/Generate Journey Script"
            scriptContent = """
                #!/usr/bin/env bash
                set -euo pipefail
                echo "##teamcity[buildStatus status='RUNNING' text='Click here to create journey!']"
                sleep 120
                
                wget \
                  --method=POST \
                  -qO- http://localhost:3002/code  \
                    | jq -r '.code' > "${'$'}{JOURNEY_NAME}_script.py"
            """.trimIndent()
        }
        script {
            id = "Generate Journey build configuration"
            scriptContent = """
                #!/usr/bin/env bash
                payload=${'$'}(cat <<EOF
                {
                  "id": "${'$'}{PROJECT_PATH_ID}_Journey_${'$'}{JOURNEY_NAME}",
                  "name": "${'$'}{JOURNEY_NAME}",
                  "projectId": "${'$'}{PROJECT_PATH_ID}",
                  "template": {
                    "id": "${'$'}{PROJECT_PATH_ID}_JourneyTemplate"
                  },
                  "parameters": {
                    "count": 2,
                    "property": [
                      {
                        "name": "JOURNEY_TYPE",
                        "value": "%JOURNEY_TYPE%"
                      },
                      {
                        "name": "JOURNEY_NAME",
                        "value": "${'$'}{JOURNEY_NAME}"
                      }
                    ]
                  },
                  "artifact-dependencies": {
                    "count": 1,
                    "artifact-dependency": [
                      {
                        "id": "ARTIFACT_DEPENDENCY_JOURNEY_SCRIPT",
                        "type": "artifact_dependency",
                        "properties": {
                          "property": [
                            {
                              "name": "cleanDestinationDirectory",
                              "value": "false"
                            },
                            {
                              "name": "pathRules",
                              "value": "${'$'}{JOURNEY_NAME}_script.py=>script"
                            },
                            {
                              "name": "revisionName",
                              "value": "buildNumber"
                            },
                            {
                              "name": "revisionValue",
                              "value": "%system.build.number%"
                            }
                          ],
                          "count": 4
                        },
                        "source-buildType": {
                          "id": "%system.teamcity.buildType.id%"
                        }
                      }
                    ]
                  },
                  "features": {
                    "count": 1,
                    "feature": [
                      {
                        "id": "swabra",
                        "type": "swabra",
                        "properties": {
                          "property": [
                            {
                              "name": "swabra.enabled",
                              "value": "swabra.before.build"
                            }
                          ],
                          "count": 1
                        }
                      }
                    ]
                  },
                  "agent-requirements": {
                    "count": 1,
                    "agent-requirement": [
                      {
                        "id": "RQ_6",
                        "type": "contains",
                        "properties": {
                          "property": [
                            {
                              "name": "property-name",
                              "value": "env.COMPATIBLE_JOURNEY_TYPES"
                            },
                            {
                              "name": "property-value",
                              "value": "%JOURNEY_TYPE%"
                            }
                          ],
                          "count": 2
                        }
                      }
                    ]
                  }
                }
                EOF
                )
                
                echo ${'$'}payload
                
                echo "##teamcity[buildStatus status='SUCCESS' text='${'$'}{JOURNEY_NAME}']"
                
                curl -i -sS --fail-with-body \
                  -H "Authorization: Bearer ${'$'}{GIT_PAT_TOKEN}" \
                  -H "Content-Type: application/json" \
                  -X POST \
                  "${'$'}{TEAMCITY_SERVER_URL}/app/rest/buildTypes" \
                  -d "${'$'}{payload}"
            """.trimIndent()
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            clearConditions()
            scriptContent = """
                #!/usr/bin/env bash
                set -euo pipefail
                echo "##teamcity[buildStatus status='RUNNING' text='Click here to create journey!']"
                
                wget \
                  --method=POST \
                  -qO- http://localhost:3002/code  \
                    | jq -r '.code' > "${'$'}{JOURNEY_NAME}_script.py"
            """.trimIndent()
            param("teamcity.kubernetes.executor.pull.policy", "")
        }
    }
}
