package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.swabra
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Journey_WikipediaJourney'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    templates(RelativeId("JourneyTemplate"))
    id("Journey_WikipediaJourney")
    name = "WikipediaJourney"

    params {
        param("JOURNEY_NAME", "WikipediaJourney")
        param("JOURNEY_TYPE", "WEB")
    }

    features {
        swabra {
            id = "swabra"
        }
    }

    dependencies {
        artifacts(RelativeId("JourneyGenerator")) {
            id = "ARTIFACT_DEPENDENCY_19"
            buildRule = build("67")
            artifactRules = "WikipediaJourney_script.py=>script"
        }
    }

    requirements {
        contains("env.COMPATIBLE_JOURNEY_TYPES", "WEB", "RQ_19")
    }
}))

