package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Journey_SixthGeneratedBuild13'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    templates(RelativeId("JourneyExecutorTemplate"))
    id("Journey_SixthGeneratedBuild13")
    name = "SixthGeneratedBuild13"

    artifactRules = "+:*.txt"

    params {
        param("journeyName", "ceva")
    }

    dependencies {
        artifacts(RelativeId("JourneyMakerV1")) {
            id = "ARTIFACT_DEPENDENCY_7"
            buildRule = build("80")
            artifactRules = "*.txt=>script.txt"
        }
    }

    requirements {
        exists("env.ADB_SERVER_SOCKET", "RQ_3")
    }
}))

