package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'WebpagesPlugin'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("WebpagesPlugin")) {
    expectSteps {
        maven {
            name = "Maven package"
            goals = "package"
            pomLocation = "pom.xml"
        }
    }
    steps {
        insert(1) {
            script {
                id = "simpleRunner"
                scriptContent = """
                    #!/usr/bin/env bash
                    set -e
                    
                    echo "${'$'}TEAMCITY_DATA_PATH/something"
                    cp target/WebpagesInTeamCityPlugin.zip "opt/teamcity/data/plugins"
                """.trimIndent()
            }
        }
    }
}
