package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        expect {
            password("GIT_AUTH_TOKEN", "credentialsJSON:f1f20dd4-912c-4977-ae90-c79dc6674b3e")
        }
        update {
            password("GIT_AUTH_TOKEN", "credentialsJSON:95b2436d-c42a-4714-b646-52db77b30b60")
        }
        add {
            password("TC_AUTH_TOKEN", "credentialsJSON:9ee1fb21-faef-4c3c-9772-988c459466c2")
        }
    }
}
