package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        expect {
            password("GIT_AUTH_TOKEN", "credentialsJSON:f1f20dd4-912c-4977-ae90-c79dc6674b3e")
        }
        update {
            password("GIT_AUTH_TOKEN", "credentialsJSON:1c87e1b0-06db-4d3a-a425-99c82850f89a")
        }
    }
}
