package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'JourneyExecutorPodInfraV2Git'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("JourneyExecutorPodInfraV2Git")) {
    val expected = GitVcsRoot({
        id("JourneyExecutorPodInfraV2Git")
        name = "%JOURNEY_EXECUTOR_GIT_ADDRESS%"
        url = "%JOURNEY_EXECUTOR_GIT_ADDRESS%"
        branch = "refs/heads/master"
        branchSpec = "refs/heads/*"
        authMethod = password {
            userName = "%GIT_USER%"
            password = "%GIT_AUTH_TOKEN%"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        authMethod = password {
            userName = "%GIT_USER%"
            password = "credentialsJSON:d342a2d2-9a3a-4345-b0f1-2af347272a83"
        }
    }

}
