package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'JourneyExecutorPodInfraV2Git'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("JourneyExecutorPodInfraV2Git")) {
    val expected = GitVcsRoot({
        id("JourneyExecutorPodInfraV2Git")
        name = "https://github.com/ChiriacCasian/pod-infra_v2.git"
        url = "https://github.com/ChiriacCasian/pod-infra_v2"
        branch = "refs/heads/master"
        authMethod = password {
            userName = "ChiriacCasian"
            password = "credentialsJSON:9b4689e5-3c42-4bfb-843e-7d0d1a023a38"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        branchSpec = "refs/heads/*"
    }

}
