package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'TCBuildServerGit'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("TCBuildServerGit")) {
    val expected = GitVcsRoot({
        id("TCBuildServerGit")
        name = "%TC_BUILDSERVER_GIT_ADDRESS%"
        url = "%TC_BUILDSERVER_GIT_ADDRESS%"
        branch = "refs/heads/main"
        authMethod = password {
            userName = "%GIT_USER%"
            password = "%GIT_AUTH_TOKEN%"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        authMethod = password {
            userName = "%GIT_USER%"
            password = "credentialsJSON:fd3bb91d-e24a-47e0-b2d9-ed2e89170f66"
        }
    }

}
