#!/usr/bin/env bash
set -euo pipefail

script_dir="./script"

# Check that there is exactly one .txt file in the script_dir
txt_files=("${script_dir}"/*.py)
if [[ ${#txt_files[@]} -ne 1 ]]; then
  echo "Error: expected exactly one .txt file in ${script_dir}, found ${#txt_files[@]}." >&2
  exit 1
fi

# Absolute path of the script
abs_path="$(readlink -f "${txt_files[0]}")"
echo "Script found: ${abs_path}"

curl -i -sS --fail-with-body \
     --data-urlencode "journeyName=%JOURNEY_NAME%" \
     --data-urlencode "scriptPath=${abs_path}" \
     --data-urlencode "type=%JOURNEY_TYPE%" \
     --data-urlencode "buildConfigurationCheckoutDir=%teamcity.build.checkoutDir%" \
     -X POST \
     http://localhost:8060/runJourney